version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      cloudflare:
        applies-to: version-updates
        patterns:
          - "@cloudflare/*"
          - "wrangler"
