// Generated by Wrangler on Sun Jun 09 2024 23:18:06 GMT+0300 (Eastern European Summer Time)
// by running `wrangler types`

interface Env {
	map_versions: KVNamespace;
	WEB_PAGE_URL: "https://help.tomtom.com/hc/en-gb/articles/360013959519-Latest-maps-for-navigation-devices";
	NOTIFY_EMAIL: string;
	SENDGRID_API_KEY: string;
}
