// Generated by Wrangler on Mon Jun 24 2024 21:34:53 GMT+0000 (Coordinated Universal Time)
// by running `wrangler types`

interface Env {
  map_versions: KVNamespace;
  map_version_changes: KVNamespace;
  WEB_PAGE_URL: "https://help.tomtom.com/hc/en-gb/articles/360013959519-Latest-maps-for-navigation-devices";
  NOTIFY_EMAIL: string;
  SENDGRID_API_KEY: string;
}
