#:schema node_modules/wrangler/config-schema.json
name = "tomtom-version"
main = "src/index.ts"
compatibility_date = "2024-06-09"

[observability]
enabled = true
head_sampling_rate = 1

# Cron Triggers
# Docs: https://developers.cloudflare.com/workers/platform/triggers/cron-triggers/
# Configuration: https://developers.cloudflare.com/workers/wrangler/configuration/#triggers
[triggers]
crons = ["0 12 * * *"] # run every day at noon UTC

[vars]
WEB_PAGE_URL = "https://help.tomtom.com/hc/en-gb/articles/360013959519-Latest-maps-for-navigation-devices"

[[kv_namespaces]]
binding = "map_versions"
id = "d84dad3b933448af81e9861948da8086"

[[kv_namespaces]]
binding = "map_version_changes"
id = "7c192d8cdc3b48b088b0407caaad4fda"
